baseURL = "https://example.org/"
title = "My big bazar"
defaultContentLanguage = "en"
theme = "dream"

[params]
  zenMode = false
  avatar = "img/avatar.png"
  lightTheme = "emerald"
  darkTheme = "forest"
  showTableOfContents = false

  [params.advanced]
    customCSS = ["css/custom.css"]

[frontmatter]
  lastmod = [":fileModTime", "lastmod", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

