baseURL = "https://example.org/"
title = "My big bazar"
defaultContentLanguage = "en"
theme = "dream"

[params]
  zenMode = false
  avatar = "img/avatar.png"
  lightTheme = "emerald"
  darkTheme = "forest"
[frontmatter]
  lastmod = [":fileModTime", "lastmod", "date"]
